"""Local fixture with the 99 routes from the API key catalog, and the list of forbidden
paths. `tests/test_routes_matrix.py` proves exact coverage and exclusion."""

from __future__ import annotations

FROZEN_ROUTES: list[tuple[str, str]] = [
    ("DELETE", "/v1/workspaces/:id"),
    ("DELETE", "/v1/workspaces/:id/invites/:invite_id"),
    ("GET", "/v1/workspaces/:id/action-requests"),
    ("GET", "/v1/workspaces/:id/invites"),
    ("GET", "/v1/workspaces/invites/:token"),
    ("POST", "/v1/workspaces/:id/action-requests"),
    ("POST", "/v1/workspaces/invites/:token/accept"),
    ("POST", "/v1/workspaces/invites/:token/decline"),
    ("DELETE", "/v1/apps/:id"),
    ("DELETE", "/v1/apps/:id/deploys/webhook"),
    ("DELETE", "/v1/apps/:id/envs/:envId"),
    ("DELETE", "/v1/apps/:id/files"),
    ("DELETE", "/v1/apps/:id/network/custom"),
    ("DELETE", "/v1/apps/:id/network/publish"),
    ("DELETE", "/v1/databases/:id"),
    ("DELETE", "/v1/users/me/favorites/:resource_type/:resource_id"),
    ("DELETE", "/v1/users/me/folders/:folder_id"),
    ("DELETE", "/v1/users/me/folders/:folder_id/resources/:resource_type/:resource_id"),
    ("DELETE", "/v1/workspaces/:id/apps/:app_id"),
    ("DELETE", "/v1/workspaces/:id/databases/:db_id"),
    ("DELETE", "/v1/workspaces/:id/members/:user_id"),
    ("DELETE", "/v1/workspaces/:id/favorites/:resource_type/:resource_id"),
    ("DELETE", "/v1/workspaces/:id/folders/:folder_id"),
    ("DELETE", "/v1/workspaces/:id/folders/:folder_id/resources/:resource_type/:resource_id"),
    ("DELETE", "/v1/workspaces/:id/roles/:role_id"),
    ("GET", "/v1/apps/:id"),
    ("GET", "/v1/apps/:id/deploys"),
    ("GET", "/v1/apps/:id/deploys/webhook"),
    ("GET", "/v1/apps/:id/download"),
    ("GET", "/v1/apps/:id/envs"),
    ("GET", "/v1/apps/:id/files"),
    ("GET", "/v1/apps/:id/files/content"),
    ("GET", "/v1/apps/:id/files/tree"),
    ("GET", "/v1/apps/:id/logs"),
    ("GET", "/v1/apps/:id/metrics"),
    ("GET", "/v1/apps/:id/network/custom"),
    ("GET", "/v1/apps/:id/network/dns"),
    ("GET", "/v1/apps/:id/realtime"),
    ("GET", "/v1/apps/:id/status"),
    ("GET", "/v1/apps/runtimes"),
    ("GET", "/v1/apps/status"),
    ("GET", "/v1/databases/:id"),
    ("GET", "/v1/databases/:id/credentials/certificate"),
    ("GET", "/v1/databases/:id/metrics"),
    ("GET", "/v1/databases/:id/status"),
    ("GET", "/v1/databases/status"),
    ("GET", "/v1/orders"),
    ("GET", "/v1/orders/:orderId/status"),
    ("GET", "/v1/users/:id/snapshots"),
    ("GET", "/v1/users/:id/snapshots/:snapshot_id/download"),
    ("GET", "/v1/users/me"),
    ("GET", "/v1/users/me/sessions"),
    ("GET", "/v1/users/snapshots"),
    ("GET", "/v1/workspaces"),
    ("GET", "/v1/workspaces/:id"),
    ("GET", "/v1/workspaces/:id/members"),
    ("GET", "/v1/workspaces/:id/roles"),
    ("PATCH", "/v1/apps/:id/config"),
    ("PATCH", "/v1/apps/:id/files"),
    ("PATCH", "/v1/apps/:id/network/subdomain"),
    ("PATCH", "/v1/users/me"),
    ("PATCH", "/v1/users/me/folders/:folder_id"),
    ("PATCH", "/v1/workspaces/:id/folders/:folder_id"),
    ("POST", "/v1/apps"),
    ("POST", "/v1/apps/:id/deploys/webhook"),
    ("POST", "/v1/apps/:id/envs"),
    ("POST", "/v1/apps/:id/files/upload"),
    ("POST", "/v1/apps/:id/network/custom"),
    ("POST", "/v1/apps/:id/network/publish"),
    ("POST", "/v1/apps/:id/network/purge-cache"),
    ("POST", "/v1/apps/:id/restart"),
    ("POST", "/v1/apps/:id/start"),
    ("POST", "/v1/apps/:id/stop"),
    ("POST", "/v1/databases"),
    ("POST", "/v1/databases/:id/credentials/certificate/reset"),
    ("POST", "/v1/databases/:id/credentials/reset"),
    ("POST", "/v1/databases/:id/reset"),
    ("POST", "/v1/databases/:id/start"),
    ("POST", "/v1/databases/:id/stop"),
    ("POST", "/v1/orders"),
    ("POST", "/v1/orders/:orderId/initiate/pix"),
    ("POST", "/v1/redeem/:code"),
    ("POST", "/v1/users/:id/snapshots"),
    ("POST", "/v1/users/:id/snapshots/:snapshot_id/restore"),
    ("POST", "/v1/users/me/folders"),
    ("POST", "/v1/workspaces"),
    ("POST", "/v1/workspaces/:id/apps/:app_id"),
    ("POST", "/v1/workspaces/:id/databases/:db_id"),
    ("POST", "/v1/workspaces/:id/folders"),
    ("POST", "/v1/workspaces/:id/roles"),
    ("PUT", "/v1/apps/:id/files"),
    ("PUT", "/v1/databases/:id"),
    ("PUT", "/v1/users/me/favorites/:resource_type/:resource_id"),
    ("PUT", "/v1/users/me/folders/:folder_id/resources/:resource_type/:resource_id"),
    ("PUT", "/v1/workspaces/:id"),
    ("PUT", "/v1/workspaces/:id/members/:user_id"),
    ("PUT", "/v1/workspaces/:id/favorites/:resource_type/:resource_id"),
    ("PUT", "/v1/workspaces/:id/folders/:folder_id/resources/:resource_type/:resource_id"),
    ("PUT", "/v1/workspaces/:id/roles/:role_id"),
]

assert len(FROZEN_ROUTES) == 99, f"expected 99 frozen routes, found {len(FROZEN_ROUTES)}"

# Forbidden paths: none of these may appear, in any form, in `src/vertracloud/**`.
FORBIDDEN_PATHS: list[str] = [
    "/v1/notifications",
    "/v1/users/me/api-keys",
    "/v1/databases/:id/data",
    "/v1/admin",
    "/internal",
    "/v1/apps/scan",
    "/v1/users/me/downgrade",
    "/transfer-ownership",
    "/approve",
    "/reject",
    "/v1/activities",
    "/activities/export",
]


def route_to_regex(path_template: str) -> str:
    """`:param` -> `[^/]+` (URL-encoded), the rest of the path is literal."""
    import re

    parts = path_template.split("/")
    pattern_parts = [r"[^/]+" if part.startswith(":") else re.escape(part) for part in parts]
    return "^" + "/".join(pattern_parts) + "$"
